package main

var x11Map = map[string]string{
	" ":  "space",
	"!":  "exclam",
	"@":  "at",
	"#":  "numbersign",
	"$":  "dollar",
	"%":  "percent",
	"^":  "asciicircum",
	"&":  "ampersand",
	"*":  "asterisk",
	"(":  "parenleft",
	")":  "parenright",
	"~":  "asciitilde",
	"`":  "grave",
	"-":  "minus",
	"_":  "underscore",
	"=":  "equal",
	"+":  "plus",
	"[":  "bracketleft",
	"]":  "bracketright",
	"{":  "braceleft",
	"}":  "braceright",
	"\\": "backslash",
	"|":  "bar",
	";":  "semicolon",
	":":  "colon",
	"'":  "apostrophe",
	"\"": "quotedbl",
	",":  "comma",
	"<":  "less",
	".":  "period",
	">":  "greater",
	"/":  "slash",
	"?":  "question",
}

var needsShift = []string{
	"~", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+",
	"Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "{", "}", "|",
	"A", "S", "D", "F", "G", "H", "J", "K", "L", "L", ":", "\"",
	"Z", "X", "C", "V", "B", "N", "M", "<", ">", "?",
}
